on: # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:
permissions: {}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with: { persist-credentials: false }
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with: { node-version-file: package.json }
      - run: npm install --global "npm@$(jq -r .engines.npm package.json)"
      - uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82 # v7
      - run: npm version && npm ci && npm test
  zizmor:
    runs-on: ubuntu-24.04
    # https://github.com/zizmorcore/zizmor-action#permissions
    permissions: { security-events: write }
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with: { persist-credentials: false }
      # yamllint disable-line rule:line-length
      - uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
# .github/workflows/check.yaml
# Copyright 2024 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
