on: # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:
permissions: {}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with: { node-version-file: package.json }
      - run: npm install --global "npm@$(jq -r .engines.npm package.json)"
      # yamllint disable-line rule:line-length
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - run: npm version && npm ci && npm test
  zizmor:
    runs-on: ubuntu-24.04
    # https://github.com/zizmorcore/zizmor-action#permissions
    permissions: { security-events: write }
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }
      # yamllint disable-line rule:line-length
      - uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
# .github/workflows/check.yaml
# Copyright 2024 Keith Maxwell
# SPDX-License-Identifier: MPL-2.0
